my_string = input('Введите произвольный текст: ')
print ('Количество символов в введённой вами строке: ', len(my_string))
print ('Ваша строка в верхнем реестре: ', my_string.upper())
print ('Ваша строка в нижнем реестре: ', my_string.lower())
print ('Ваша строка без пробелов: ', my_string.replace(' ',''))
print ('Первый символ вашей строки: ', my_string[0])
print ('Последний символ вашей строки: ', my_string[-1])